# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4646986e1c2ade1f796f5b44fe04d39a5db39a4fc6f2906d2dd948c9ae71cf411ea799632f9a0fea729f1bbc759962b45a74d64ddfa906ec71c572c36995a4ab

test:
  secret_key_base: 04249ee1d06698c8c109c5e1cf8608fe2237d0fd949cffff259bb240a4db3ba02d81fecc10c667f09272de3231567d7411108f2f8f8fa46d770ce2c0f3b574c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
